name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      REACT_APP_API_KEY: ${{ secrets.API_KEY}}
      REACT_APP_AUTH_DOMAIN: ${{ secrets.APP_AUTH_DOMAIN }}
      REACT_APP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REACT_APP_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
      REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
      REACT_APP_APP_ID: ${{ secrets.APP_ID }}
      REACT_APP_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
  
      - name: List output files
        run: find build/ -print
      
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: mikahimself.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: /todo.mikahimself.com/
